#!/usr/bin/env bash
# Script to create a zipped file for an sql dump

# date formated
date=$(date '+%d-%m-%Y')

#Carry out SQL dump
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$date.tar.gz" backup.sql
