#!/usr/bin/env bash
# Fix holberton server to be accessible on port 8080
IP="$(curl ifconfig.me)"

# Set ServerName to IP
sudo sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf

sudo service apache2 start
